### PR TITLE
Reduce tilequeue seed memory usage

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/tilezen/tilequeue/issues/125

The seed command was realizing all coordinates in memory to print out the total count before enqueueing. This eliminates that and goes through an intermediary in-memory queue to keep the total memory footprint smaller.

@zerebubuth, @nvkelso, @iandees could you review please?

### CODE REVIEW

**Comment by iandees** [comment]
Can we rewrite the seeder to use a Python generator function instead of passing around a queue? That'd save memory and be a bit more pythonic/cleaner.

**Comment by rmarianski** [comment]
It does use a generator to come up with the list of tiles, but it sticks that onto separate queues for threading purposes. I don't see a good way to do it without queues and keep multi-threading.

**Comment by iandees** [comment]
Gotcha, makes sense 👍.

I think I was thinking of a different bit of code that I was experimenting with when handling the tiles of interest list, but can't find it now.

**Comment by rmarianski** [comment]
> I think I was thinking of a different bit of code that I was experimenting with when handling the tiles of interest list, but can't find it now.

Related to https://github.com/tilezen/tilequeue/pull/122 maybe?

It's very possibly, likely even, that you came across code that could be cleaner :) Feel free to submit a pr to improve it or flag it via an issue to come back to it later.

**Pull request merged**
