### PR TITLE
Log coordinates as integers

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/tile-tasks/issues/290

### CODE REVIEW

**Comment by zerebubuth** [comment]
Is this intended to trim trailing zeroes, e.g: print out as `{"z": 3, "x": 4, "y": 5}` rather than `{"z": 3.0, "x": 4.0, "y": 5.0}`?

I'm fairly sure that, in some circumstances, we might have fractional coordinates and it would be good to know about that when they're printed out. Perhaps we could integerise if the coordinate is within an *ulp* of being an integer already?

**Comment by rmarianski** [comment]
> Is this intended to trim trailing zeroes, e.g: print out as {"z": 3, "x": 4, "y": 5} rather than {"z": 3.0, "x": 4.0, "y": 5.0}?

Yes, exactly this.

> I'm fairly sure that, in some circumstances, we might have fractional coordinates and it would be good to know about that when they're printed out. Perhaps we could integerise if the coordinate is within an ulp of being an integer already?

Really, when? Happy to just coerce to int if it's an even integer, but just curious when we would come across this scenario.

**Comment by zerebubuth** [comment]
> Really, when? Happy to just coerce to int if it's an even integer, but just curious when we would come across this scenario.

The `row` and `column` of a `Coordinate` can be fractional if we zoom out and forget to call `.container()`. I can't think of an occasion where we do that deliberately, so perhaps the most likely source is a bug. But if it is a bug, and it's causing problems, then I think it would be much easier to notice if it's logged out as fractional.

**Comment by rmarianski** [comment]
Ah ok, that's fair. Updated in 972c227.

**Comment by rmarianski** [comment]
Assuming this is ok now and merging in. Let me know if there's some further follow up.

**Pull request merged**
