### PR TITLE
Update wof projection to 3857

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/tilezen/vector-datasource/issues/908

This should only get merged in once the hstore-all branch in vector-datasource does.

@zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Is it worth pulling 3857 out as `DATABASE_SRID`, a module level constant or something like that?

**Comment by rmarianski** [comment]
Sure, is ffcb329 what you had in mind?

**Comment by rmarianski** [comment]
I snuck in a fix for data insertion in cbc5166.

**Comment by zerebubuth** [comment]
Looks great, :+1:

**Comment by zerebubuth** [comment]
Oh, nice catch! Do we need that anywhere else as well? Presumably all the OSM tables are okay, since `osm2pgsql` must be doing something similar?

**Comment by rmarianski** [comment]
Turns out that 45099b6 is also needed.

I think this is specific to the initial wof load and the `copy` format. I expect other places should be ok if they go through the driver.

**Pull request merged**
